### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by joedawson** [CaptainRoss/Sailor#8]
Hey Ross,

I'm unable to see the demo - https://rossmacphee.com/Sailor/

> rossmacphee.com’s server DNS address could not be found.

Is it anywhere else to view?

**Comment by rossyman** [comment]
Sorry about that, I'll get on it 😃

**Comment by rossyman** [comment]
Enjoy - https://formatted.design/sailor/

Thanks for checking the theme out ❤️
